apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

patchesStrategicMerge:
- replica-patch.yaml
- resource-patch.yaml

configMapGenerator:
- name: kubellm-config
  behavior: merge
  literals:
  - LOG_LEVEL=warn
  - DATABASE_URL=mysql://kubellm:password@prod-mysql:3306/kubellm_prod

images:
- name: ghcr.io/bryaneanders/kubellm-api:latest
  newTag: v1.0.0
- name: ghcr.io/bryaneanders/kubellm-webapp:latest
  newTag: v1.0.0
- name: ghcr.io/bryaneanders/kubellm-cli:latest
  newTag: v1.0.0