apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-kubellm-api
spec:
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"