apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: kubellm
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: kubellm
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: kubellm
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: mysql-init
          image: mysql:8.0
          command: [ 'sh', '-c', 'cp /scripts/* /docker-entrypoint-initdb.d/' ]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 999  # mysql user
            runAsGroup: 999
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: init-scripts
              mountPath: /scripts
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql


        env:
        - name: MYSQL_DATABASE
          value: kubellm
        - name: MYSQL_USER
          value: kubellm
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "true"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 999
          runAsGroup: 999
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - bash
              - -c
              - mysql -u kubellm -p$MYSQL_PASSWORD -e "SELECT 1"
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: tmp
          mountPath: /tmp
        - name: init-scripts
          mountPath: /scripts
        - name: init-db
          mountPath: /docker-entrypoint-initdb.d

      volumes:
      - name: tmp
        emptyDir: {}
      - name: init-scripts
        configMap:
          name: mysql-init-scripts
      - name: init-db
        emptyDir: { }
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi