apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubellm-api
spec:
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"