apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubellm-webapp
spec:
  template:
    spec:
      containers:
        - name: webapp
          envFrom:
            - secretRef:
                name: dev-api-keys