apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubellm-api
spec:
  template:
    spec:
      containers:
        - name: api
          envFrom:
            - secretRef:
                name: dev-api-keys