apiVersion: batch/v1
kind: Job
metadata:
  name: kubellm-cli
spec:
  template:
    spec:
      containers:
        - name: cli
          envFrom:
            - secretRef:
                name: dev-api-keys